package mfu.oodp.view;

import mfu.oodp.controller.AccountController;
import mfu.oodp.model.Account;

import javax.swing.*;
import org.jdesktop.swingx.JXFrame;
import java.awt.*;

public class AccountCreationView extends JXFrame {
    private final AccountController accountController;
    private static int accountIdCounter = 1; // ✅ Static counter for sequential Account IDs

    public AccountCreationView(AccountController controller, String username) { // ✅ Pass username from login/registration
        super("Create New Account");
        this.accountController = controller;

        setSize(400, 300);
        setLayout(new GridLayout(6, 2));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // ✅ Generate sequential Account ID
        String autoGeneratedAccountId = String.valueOf(accountIdCounter++);

        // ✅ Use username for Account Name
        JTextField accountIdField = new JTextField(autoGeneratedAccountId);
        accountIdField.setEditable(false); // Make the Account ID field read-only
        JTextField accountNameField = new JTextField(username); // Set username as Account Name
        accountNameField.setEditable(false); // Make the Account Name field read-only
        JComboBox<String> accountTypeBox = new JComboBox<>(new String[]{"SAVINGS", "CHECKING", "LOAN"});
        JTextField initialBalanceField = new JTextField();

        JButton createBtn = new JButton("Create Account");

        add(new JLabel("Account ID:"));
        add(accountIdField);
        add(new JLabel("Account Name:"));
        add(accountNameField);
        add(new JLabel("Account Type:"));
        add(accountTypeBox);
        add(new JLabel("Initial Balance:"));
        add(initialBalanceField);
        add(new JLabel(""));
        add(createBtn);

        createBtn.addActionListener(e -> {
            try {
                // ✅ Use auto-generated Account ID and username
                String id = autoGeneratedAccountId;
                String name = username;
                String typeStr = (String) accountTypeBox.getSelectedItem();
                double balance = Double.parseDouble(initialBalanceField.getText());

                Account acc = accountController.createAccount(id, name, Account.AccountType.valueOf(typeStr), balance);
                JOptionPane.showMessageDialog(this, "✅ Account Created: " + acc.getAccountId());
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "❌ Error: " + ex.getMessage());
            }
        });
    }
}